pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:7.0'
            args '-v C:/Users/5047449/Documents/RiderProjects/JenkinsApp/JenkinsApp/Container:/var/run/docker.sock'
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/g-loopsee/JenkinsApp.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'dotnet build --configuration Release'
            }
        }
        
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'bin/Release/JenkinsApp.exe', fingerprint: true
            }
        }
    }
}
