pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:7.0'
            args '-v /var/run/docker.sock:/var/run/docker.sock -v ${WORKSPACE}:/workspace -w /workspace'
        }
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/g-loopsee/JenkinsApp.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'docker run -v ${WORKSPACE}:/workspace -w /workspace mcr.microsoft.com/dotnet/sdk:7.0 dotnet build --configuration Release'
            }
        }
        
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'bin/Release/JenkinsApp.exe', fingerprint: true
            }
        }
    }
}
