pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/g-loopsee/JenkinsApp.git'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    docker.image('mcr.microsoft.com/devcontainers/dotnet:dev-7.0').inside('-v /var/run/docker.sock:/var/run/docker.sock') {
                        sh 'dotnet build --configuration Release'
                    }
                }
            }
        }
        
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'bin/Release/JenkinsApp.exe', fingerprint: true
            }
        }
    }
}
